
word_list_animals = ('baboon badger bat bear beaver buffalo camel cat clam cobra cougar '
         'coyote chicken crow deer dog donkey duck eagle ferret fox frog goat '
         'goose hawk lion lizard llama mole monkey moose mouse mule newt '
         'otter owl panda parrot pigeon python rabbit ram rat raven '
         'rhino salmon seal shark sheep skunk sloth snake spider '
         'stork swan tiger toad trout turkey turtle weasel whale wolf '
         'wombat zebra '
         'ant beetle butterfly bedbug bee bumblebee caterpillar cicada '
         'cockroach cricket dragonfly firefly flea fly gnat grasshopper '
         'hornet junebug ladybug larva lice locust maggot mantis mayfly '
         'mosquito moth roach scarab silkworm silverfish spider stickbug '
         'termite wasp waterbug weevil ').split()

word_list_food = ('apple banana cherry orange lemon grap mango watermelon ramen rice pork chicken soup '
                  'yogurt milk beetroot pickles burger sandwich risotto spaghetti pasta macaroni ravioli '
                  'konjac grapefruit chocolate strawberry blueberry raspberry ketchup mustard sausage '
                  'mushroom onion pepper chili curry lettuce cucumber cabbage mayonnaise salad cake pizza '
                  'taco fries lasagna salt cheesecake cookies biscuit pepperoni pineapple coconut durian '
                  'marzipan meringue bolognese pesto hummus carrot zucchini venison honey pancakes waffles '
                  'nutella peanut butter cheese cheddar fetta spinach mozzarella gorgonzola steak milkshake '
                  'juice alcohol coffee meat bruschetta bread whiskey popsicle corndog popcorn candy toast '
                  'brandy arancini tteokbokki sushi onigiri tangerine plum peach eggplant garlic vinegar '
                  'takoyaki crackers beef chickpea pie profiteroles croissant donut syrup lychee rambutan dumpling '
                  'gyoza wafers paella pannacotta chips wine tomato potato passionfruit dragonfruit nectarine '
                  'pudding mochi smoothie lollipop cream vanilla ice matcha soda rosemary basil thyme cinnamon '
                  'papaya rockmelon ginger beans espresso latte frappe pear mandarine honeydew cantaloupe '
                  'apricot cauliflower broccoli pumpkin asparagus shallot tofu flour peas kale jackfruit '
                  'pomegranate starfruit lime corn artichoke avocado celery radish daikon leek parsnip '
                  'rhubarb squash chestnut almond macadamia cashew hazelnut pecan pistachio sesame walnut '
                  'nutmeg miso eggnog cilantro ').split()

word_list_countries = ('Afghanistan Albania Algeria Andorra Angola Argentina Armenia Australia Austria Azerbaijan '
                    'Bahamas Bahrain Bangladesh Barbados Belarus Belgium Belize Benin Bhutan Bolivia Bosnia '
                    'Botswana Brazil Brunei Bulgaria Burma Burundi Cambodia Cameroon Canada Chad Chile China Comoros'
                    'Croatia Cuba Cyprus Czechia Denmark Djibouti Dominica Ecuador Egypt Eritrea Estonia Eswatini '
                    'Ethiopia Fiji Finland France Gabon Georgia Germany Ghana Greece Grenada Guatemala Guinea '
                    'Haiti Honduras Hungary Iceland India Indonesia Iran Iraq Ireland Israel Italy Jamaica Japan '
                    'Jordan Kazakhstan Kenya Kiribati NorthKorea SouthKorea Laos Latvia Lebanon Lesotho Liberia Libya Liechtenstein '
                    'Lithuania Luxembourg Macedonia Madagascar Malawi Malaysia Maldives Mali Malta Mauritania Mauritius '
                    'Mexico Micronesia Moldova Monaco Mongolia Montenegro Morocco Mozambique Namibia Nauru Nepal Netherlands'
                    'NewZealand Nicaragua Niger Nigeria Norway Oman Pakistan Palau Panama PapuaNewGuinea Paraguay Peru Philippines '
                    'Poland Portugal Qatar Romania Russia Rwanda Samoa SaudiArabia Senegal Serbia Seychelles SierraLeone '
                    'Singapore Slovakia Slovenia SolomonIslands Somalia SouthAfrica Spain SriLanka Sudan Suriname Sweden '
                    'Switzerland Syria Tajikistan Tanzania Thailand Togo Tonga Tunisia Turkey Turkmenistan Tuvalu Uganda '
                    'Ukraine UnitedArabEmirates UnitedKingdom England Britain America Uruguay Uzbekistan Vanuatu VaticanCity '
                    'Venezuela Vietnam Yemen Zambia Zimbabwe '
                    '').lower().split()

word_list_misc = ('about, above, abuse, accept, accident, accuse, across, activist, actor, administration, '
                  'admit, adult, advertise, advise, affect, afraid, after, again, against, agency, aggression, '
                  'agree, agriculture, force, airplane, airport, album, alive, almost, alone, along, '
                  'already, although, always, ambassador, amend, ammunition, among, amount, anarchy, ancestor, '
                  'ancient, anger, animal, anniversary, announce, another, answer, apologize, appeal, appear, '
                  'appoint, approve, archeology, argue, around, arrest, arrive, artillery, assist, astronaut, '
                  'astronomy, asylum, atmosphere, attach, attack, attempt, attend, attention, automobile, autumn, '
                  'available, average, avoid, awake, award, balance, balloon, ballot, barrier, battle, beauty, because, '
                  'become, before, begin, behavior, behind, believe, belong, below, betray, better, between, biology, '
                  'black, blame, bleed, blind, block, blood, border, borrow, bottle, bottom, boycott, brain, brave, '
                  'bread, break, breathe, bridge, brief, bright, bring, broadcast, brother, brown, budget, build, '
                  'building, bullet, burst, business, cabinet, camera, campaign, cancel, cancer, candidate, capital, '
                  'capture, career, careful, carry, catch, cause, ceasefire, celebrate, center, century, ceremony, '
                  'chairman, champion, chance, change, charge, chase, cheat, cheer, chemicals, chemistry, chief, child, '
                  'children, choose, circle, citizen, civilian, civil, rights, claim, clash, class, clean, clear, clergy, '
                  'climate, climb, clock, close, cloth, clothes, cloud, coalition, coast, collapse, collect, college, '
                  'colony, color, combine, command, comment, committee, common, communicate, community, company, compare, '
                  'compete, complete, complex, compromise, computer, concern, condemn, condition, conference, confirm, '
                  'conflict, congratulate, Congress, connect, conservative, consider, constitution, contact, contain, '
                  'container, continent, continue, control, convention, cooperate, correct, corruption, cotton, count, '
                  'country, court, cover, crash, create, creature, credit, crime, criminal, crisis, criticize, crops, '
                  'cross, crowd, crush, culture, curfew, current, custom, customs, damage, dance, danger, daughter, '
                  'debate, decide, declare, decrease, defeat, defend, deficit, define, degree, delay, delegate, demand, '
                  'democracy, demonstrate, denounce, depend, deplore, deploy, depression, describe, desert, design, '
                  'desire, destroy, detail, detain, develop, device, dictator, different, difficult, dinner, diplomat, '
                  'direct, direction, disappear, disarm, disaster, discover, discrimination, discuss, disease, dismiss, '
                  'dispute, dissident, distance, divide, doctor, document, dollar, donate, double, dream, drink, drive, '
                  'drown, during, early, earth, earthquake, ecology, economy, education, effect, effort, either, elect, '
                  'electricity, embassy, embryo, emergency, emotion, employ, empty, enemy, energy, enforce, engine, '
                  'engineer, enjoy, enough, enter, environment, equal, equipment, escape, especially, establish, estimate, '
                  'ethnic, evaporate, event, every, evidence, exact, examine, example, excellent, except, exchange, excuse, '
                  'execute, exercise, exile, exist, expand, expect, expel, experience, experiment, expert, explain, explode, '
                  'explore, export, express, extend, extra, extraordinary, extreme, extremist, factory, false, family, famous, '
                  'father, favorite, federal, female, fence, fertile, field, fierce, fight, final, financial, finish, fireworks, '
                  'first, float, flood, floor, flower, fluid, follow, force, foreign, forest, forget, forgive, former, '
                  'forward, freedom, freeze, fresh, friend, frighten, front, fruit, funeral, future, gather, general, '
                  'generation, genocide, gentle, glass, goods, govern, government, grain, grass, great, green, grind, ground, '
                  'group, guarantee, guard, guerrilla, guide, guilty, happen, happy, harvest, headquarters, health, heavy, '
                  'helicopter, hijack, history, holiday, honest, honor, horrible, horse, hospital, hostage, hostile, hotel, '
                  'house, however, human, humor, hunger, hurry, husband, identify, ignore, illegal, imagine, immediate, '
                  'immigrant, import, important, improve, incident, incite, include, increase, independent, individual, '
                  'industry, infect, inflation, influence, inform, information, inject, injure, innocent, insane, insect, '
                  'inspect, instead, instrument, insult, intelligence, intelligent, intense, interest, interfere, international, '
                  'Internet, intervene, invade, invent, invest, investigate, invite, involve, island, issue, jewel, joint, '
                  'judge, justice, kidnap, knife, knowledge, labor, laboratory, language, large, laugh, launch, learn, leave, '
                  'legal, legislature, letter, level, liberal, light, lightning, limit, liquid, listen, literature, little, '
                  'local, lonely, loyal, machine, magazine, major, majority, manufacture, march, market, marry, material, '
                  'mathematics, matter, mayor, measure, media, medicine, member, memorial, memory, mental, message, metal, '
                  'method, microscope, middle, militant, military, militia, mineral, minister, minor, minority, minute, '
                  'missile, missing, mistake, model, moderate, modern, money, month, moral, morning, mother, motion, mountain, '
                  'mourn, movement, movie, murder, music, mystery, narrow, nation, native, natural, nature, necessary, '
                  'negotiate, neighbor, neither, neutral, never, night, noise, nominate, normal, north, nothing, nowhere, '
                  'nuclear, number, object, observe, occupy, ocean, offensive, offer, office, officer, official, often, '
                  'operate, opinion, oppose, opposite, oppress, orbit, order, organize, other, overthrow, paint, paper, '
                  'parachute, parade, pardon, parent, parliament, partner, party, passenger, passport, patient, peace, '
                  'people, percent, perfect, perform, period, permanent, permit, person, persuade, physical, physics, '
                  'picture, piece, pilot, place, planet, plant, plastic, please, plenty, point, poison, police, policy, '
                  'politics, pollute, popular, population, position, possess, possible, postpone, poverty, power, praise, '
                  'predict, pregnant, present, president, press, pressure, prevent, price, prison, private, prize, probably, '
                  'problem, process, produce, profession, professor, profit, program, progress, project, promise, propaganda, '
                  'property, propose, protect, protest, prove, provide, public, publication, publish, punish, purchase, purpose, '
                  'quality, question, quick, quiet, radar, radiation, radio, railroad, raise, reach, react, ready, realistic, '
                  'reason, reasonable, rebel, receive, recent, recession, recognize, record, recover, reduce, reform, refugee, '
                  'refuse, register, regret, reject, relations, release, religion, remain, remains, remember, remove, repair, '
                  'repeat, report, represent, repress, request, require, rescue, research, resign, resist, resolution, '
                  'resource, respect, responsible, restaurant, restrain, restrict, result, retire, return, revolt, right, '
                  'river, rocket, rough, round, rubber, rural, sabotage, sacrifice, sailor, satellite, satisfy, school, '
                  'science, search, season, second, secret, security, seeking, seize, Senate, sense, sentence, separate, '
                  'series, serious, serve, service, settle, several, severe, shake, shape, share, sharp, sheep, shell, '
                  'shelter, shine, shock, shoot, short, should, shout, shrink, sickness, signal, silence, silver, similar, '
                  'simple, since, single, sister, situation, skeleton, skill, slave, sleep, slide, small, smash, smell, smoke, '
                  'smooth, social, soldier, solid, solve, sound, south, space, speak, special, speech, speed, spend, spill, '
                  'spirit, split, sport, spread, spring, square, stand, start, starve, state, station, statue, steal, steam, '
                  'steel, stick, still, stone, store, storm, story, stove, straight, strange, street, stretch, strike, strong, '
                  'structure, struggle, study, stupid, subject, submarine, substance, substitute, subversion, succeed, sudden, '
                  'suffer, sugar, suggest, suicide, summer, supervise, supply, support, suppose, suppress, surface, surplus, '
                  'surprise, surrender, surround, survive, suspect, suspend, swallow, swear, sweet, sympathy, system, target, '
                  'taste, teach, technical, technology, telephone, telescope, television, temperature, temporary, tense, '
                  'terrible, territory, terror, terrorist, thank, theater, theory, there, these, thick, thing, think, third, '
                  'threaten, through, throw, tired, today, together, tomorrow, tonight, torture, total, touch, toward, trade, '
                  'tradition, traffic, tragic, train, transport, transportation, travel, treason, treasure, treat, treatment, '
                  'treaty, trial, tribe, trick, troops, trouble, truce, truck, trust, under, understand, unite, universe, '
                  'university, unless, until, urgent, usual, vacation, vaccine, valley, value, vegetable, vehicle, version, '
                  'victim, victory, video, village, violate, violence, visit, voice, volcano, volunteer, wages, waste, watch, '
                  'water, wealth, weapon, weather, weigh, welcome, wheat, wheel, where, whether, which, while, white, whole, '
                  'willing, window, winter, withdraw, without, witness, woman, wonder, wonderful, world, worry, worse, worth, '
                  'wound, wreck, wreckage, write, wrong, yellow, yesterday, young').split(", ")
